### ISSUE TITLE
syntaxerror

### ISSUE THREAD

**Issue by adamjimenez** [a-zb/dropfuse#1]
Think I'm doing this right but am getting syntax errors:

python dropfuse.py https://www.dropbox.com/s/c6ecc2plwconh5x mnt/

Traceback (most recent call last):
  File "dropfuse.py", line 10, in ?
    from fuse import *
  File "/*/fuse.py", line 276
    args.append(','.join(key if val == True else '%s=%s' % (key, val)

SyntaxError: invalid syntax

**Comment by a-zb** [comment]
Which version of python ( python -V ) are you using?
Which version of fuse libraries do you have? Under Ubuntu, this package is called
libfuse-dev. Try to run : sudo apt-cache show libfuse-dev

**Comment by adamjimenez** [comment]
Centos 5.5
Python 2.4.3
fuse-2.7.4-8.el5
fuse-devel 2.7.4-8.el5

**Comment by a-zb** [comment]
Ok, 

This is related to the outdated version of Python. If possible, install at least Python 2.6 and the syntax error will go away. If you choose to stay with 2.4, I'll need to make the fuse python code backwards compatible. You will need to install ctypes module as well, because it's not part of Python before version 2.5

I'm not sure if it's worth the hassle as Python 2.4 is not widely used.

**Comment by adamjimenez** [comment]
Thanks for getting back to me. This is the latest version of Python available in Centos 5.5. 

Centos 5.6 should be out soon. Hopefully that will have a the right version.
